### ISSUE TITLE
buildout fail

### ISSUE THREAD

**Issue by schsa-helpdesk** [plone/simple-plone-buildout#7]
PS C:\simple-plone-buildout> env/Scripts/buildout
Creating directory 'C:\\simple-plone-buildout\\eggs'.
Couldn't find index page for 'jarn.setuptoolsfixer' (maybe misspelled?)
Getting distribution for 'jarn.setuptoolsfixer'.
Couldn't find index page for 'jarn.setuptoolsfixer' (maybe misspelled?)
While:
  Installing.
  Loading extensions.
  Getting distribution for 'jarn.setuptoolsfixer'.
Error: Couldn't find a distribution for 'jarn.setuptoolsfixer'.

**Comment by tkimnguyen** [comment]
This is because of a setuptools change that requires using https instead of http to download eggs. Please see https://community.plone.org/t/buildout-not-working-disabling-non-https-access-to-apis-on-pypi/5069/30 for a temporary workaround

**Comment by tkimnguyen** [comment]
Adding this line in your buildout.cfg in the `[buildout]` section will get you around the problem:

```index = https://pypi.python.org/simple/```

Am testing this change.

**Comment by tkimnguyen** [comment]
Fixed by https://github.com/plone/simple-plone-buildout/commit/7d2ad02815dbe472d79090be016cff8a0df2ddbf

**Comment by tkimnguyen** [comment]
@schsa-helpdesk thanks for reporting it!
